version: '3.8'

services:
  web:
    build: .
    command: gunicorn -c gunicorn_config.py core.wsgi:application
    volumes:
      - .:/app
      - static_volume:/app/staticfiles
    ports:
      - "80:80"
    env_file:
      - .env

volumes:
  static_volume: